camunda.bpm.client:
  base-url: http://localhost:8080/engine-rest
  subscriptions:
    deductCredit:
      variable-names: [customerId,orderTotal]
logging:
  level:
    root: info
    org:
      apache:
        http: info
      camunda:
        bpm:
          client: debug
camunda:
  bpm:
    client:
      async-response-timeout: 60000
      disable-backoff-strategy: false


